= Listing de mes mémos, tips et autres

== Angular / NgRx

. [Mémo] GDG Toulouse - Faire du Redux avec Angular et NgRx v4 (Bruno Baia) +
https://gist.github.com/jprivet-dev/14c32852313b310d6e60c3e92b733c26

== PHP / Symfony

. [Mémo] Forum PHP 2017 - Écrire des tests pour le long terme (Charles Desneuf) +
https://gist.github.com/jprivet-dev/6d8e8f3a439936816726c5f36e146e4d
. [Tips] SymfonyLive Paris 2016 - Comment mettre à jour 30 000 produits avec Doctrine2 ? (André Tapia & Amine Mokeddem) +
https://gist.github.com/jprivet-dev/d0c9929378921f642703f2c96fbee0a3
. [Mémo] AFUP - PHP Tour 2012 - Symfony, Design Pattern Observer, injection de dépendance et Service Locator (Hugo Hamon) +
https://gist.github.com/jprivet-dev/8ced5058f843074b88a0dbe90ec1112d

== Git

. Git and Bash aliases defined and documented in a single `.bash_aliases` file, with Git auto-completion +
https://gist.github.com/jprivet-dev/09912ca4188a4ba3c610d7f61c200c38

. Transfer a Gist into a new GitHub repository +
https://gist.github.com/jprivet-dev/6e7e81c3c0497a6292dd760559840fb1

. Set up a global .gitignore file to avoid committing files like .DS_Store, Vim swp files, PHPStorm idea files, etc +
https://gist.github.com/jprivet-dev/441ca36c4368fe72d52de993aa0dfe47

. Composer: Generate a Github Oauth token for privately hosted packages and repositories +
https://gist.github.com/jprivet-dev/26e27af0b5fb3e2c219c9fe1ebcf793f

== Markdown & Asciidoctor

. [Cheatsheet] Markdown & Asciidoctor rendering in GitHub +
https://gist.github.com/jprivet-dev/88c9c74561e78c2a7f06858e1eac56ff

. README.adoc for GitHub (startup Asciidoctor template) +
https://gist.github.com/jprivet-dev/c4ab3272506a4e1eb05dd11dcb117eaf

== Autres

. Shorcuts (PHPStorm, Chrome, …) +
https://gist.github.com/jprivet-dev/87fcc531644243b7026d32e86740d8a7


